name: CI
on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  rubocop-test:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.57.0
        with: 
          ruby-version: 2.6.6
      - name: Install Rubocop Gem
        run: |
          gem install rubocop
      - name: Run rubocop
        run: |
          rubocop
